version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase started
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain alextest --domain-owner 773784969518 --region us-east-1 --query authorizationToken --output text`

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p tests
      - python -m unittest discover tests
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts
artifacts:
  files:
    - "**/*.py"
    - "requirements.txt"
    - "templates/**/*"
  discard-paths: no
